name: Docker mcr.microsoft.com/dotnet/sdk:8.0-focal

on:
  pull_request:
    types: [synchronize, opened]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
          
      - name: docker build
        run: |
          cd docker/ubuntu22-dotnet6sdk-opencv4.7.0
          docker build -t JreeyPaladin/ubuntu22-dotnet8sdk-opencv4.7.0 .
